//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.24 at 10:20:31 PM CEST 
//
package cz.rk.vocloud.schema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for worker complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="worker">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="restricted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="binaries-location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exec-command" type="{http://vocloud.rk.cz/schema}command-list"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "worker", propOrder = {
    "identifier",
    "description",
    "restricted",
    "binariesLocation",
    "execCommand"
})
public class Worker implements Serializable {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String identifier;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(defaultValue = "false")
    protected boolean restricted;
    @XmlElement(name = "binaries-location", required = true)
    protected String binariesLocation;
    @XmlElement(name = "exec-command", required = true)
    protected CommandList execCommand;

    /**
     * Gets the value of the identifier property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the restricted property.
     *
     */
    public boolean isRestricted() {
        return restricted;
    }

    /**
     * Sets the value of the restricted property.
     *
     */
    public void setRestricted(boolean value) {
        this.restricted = value;
    }

    /**
     * Gets the value of the binariesLocation property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBinariesLocation() {
        return binariesLocation;
    }

    /**
     * Sets the value of the binariesLocation property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setBinariesLocation(String value) {
        this.binariesLocation = value;
    }

    /**
     * Gets the value of the execCommand property.
     *
     * @return possible object is {@link CommandList }
     *
     */
    public CommandList getExecCommand() {
        return execCommand;
    }

    /**
     * Sets the value of the execCommand property.
     *
     * @param value allowed object is {@link CommandList }
     *
     */
    public void setExecCommand(CommandList value) {
        this.execCommand = value;
    }

}
